// Generated by CoffeeScript 1.4.0
(function() {

  this.Markers = {
    addMarker: function(marker, infoWindow) {
      marker = new google.maps.Marker(this.markerOptions(marker));
      this.markers.push(marker);
      return marker;
    },
    markerOptions: function(options) {
      var _ref;
      return {
        map: this.map,
        position: this.markerPosition(options),
        icon: ((_ref = this.settings.markers) != null ? _ref.icon : void 0) != null ? this.settings.markers.icon : void 0
      };
    },
    markerPosition: function(options) {
      if (options.center != null) {
        return this.latLng(this.center().lat, this.center().lng);
      } else {
        return this.latLng(options.lat, options.lng);
      }
    },
    destroyMarker: function(markerToDelete) {
      markerToDelete.setMap(null);
      return this.markers = this.markers.filter(function(marker) {
        return marker !== markerToDelete;
      });
    },
    destroyMarkers: function() {
      var marker, _i, _len, _ref, _results;
      _ref = this.markers;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        marker = _ref[_i];
        _results.push(this.destroyMarker(marker));
      }
      return _results;
    }
  };

}).call(this);
